### PR TITLE
Added Pwnagotchi support

### PR DESCRIPTION
**Pull request by cyberartemio**
I added the ability to run the `wall_of_flippers` mode directly from the invocation without having to use the interactive ui.

The reason I made this change is to be able to run Wall of Flippers in the background as a systemd process. Mainly I did it so that it is possible to run the script on Pwnagotchi then using the plugin I made to see the name of the Flipper on the display, but the same thing can be done on any Linux system (except for the plugin of course).

I also added the instructions in the README about installing on the pwnagotchi trying to follow the current style.

For now the only mode that is possible to invoke from the command line is the `wall_of_flippers` mode, but it should be quick to add the other modes as well.

Last thing: when in no-ui mode all banner printing is disabled and only logged when a Flipper device changes from offline to online and vice versa, this is because the logs are looked at periodically.

I tried to touch as little of the existing code as possible, adding only the bare minimum.

### CODE REVIEW

**Comment by K3YOMI** [comment]
I'll take a look when I can. I did notice that one of features *hci selection* was being skipped on windows resulting in hci_device not being defined

**Comment by cyberartemio** [comment]
> I did notice that one of features _hci selection_ was being skipped on windows resulting in hci_device not being defined

I tried to run it on Windows (both, using interactive ui and using cli args) but can't reproduce the error. Can you add more details/how to reproduce it so I can push a fix?

**Comment by K3YOMI** [comment]
Thank you, don't seem to have the issue anymore. Will take a further look when I get back and have time 👍

**Comment by cyberartemio** [comment]
I updated the README.md documentation for the systemd service because after writing to NerdyJedi for #22, while debugging the problem we saw that the service docs wasn't updated (I forgot to push the updated version). Now it's fixed and working. Also #22 is solved.

**Pull request closed without merging**
