### PR TITLE
Added Fedora installation guide and refined Auto installation.

### PR DESCRIPTION
**Pull request by OnlyNandan**
Fedora installation documentation and edited the python code to check the distro and auto install as per the linux distro the python program is being run on

### CODE REVIEW

**Comment by K3YOMI** [comment]
Oh nice, I'll take a look when I can!

**Comment by OnlyNandan** [comment]
Sure :D

**Comment by K3YOMI** [comment]
I've noticed a few things. A new python package would be required. Documentation looks great, I just would prefer another method for the auto install process. Could this be replaced with `import platform` and use `platform.freedesktop_os_release()`

**Comment by OnlyNandan** [comment]
Ahh yeah sure ill make the changes for it to use platform. Yeah I have tested it on Fedora on my system and debian on a vm. There were no bugs as such other than the Functionality of the program not working in the vm due to unsupported bluetooth driver.

**Comment by K3YOMI** [comment]
> Ahh yeah sure ill make the changes for it to use platform. Yeah I have tested it on Fedora on my system and debian on a vm. There were no bugs as such other than the Functionality of the program not working in the vm due to unsupported bluetooth driver.

Yeah, I was having an issue with bluepy library with a fresh vm install.

**Comment by OnlyNandan** [comment]
Ohh i just tried after updating to platform module in debian vm and bluepy installed but 
image 

with fedora it works all properly

**Comment by K3YOMI** [comment]
Ah, Thats because you dont have BT

**Comment by OnlyNandan** [comment]
ohh cool then the installation works check it out when you get time.

**Comment by K3YOMI** [comment]
I got it to work finally lol, let me double check a few things

**Comment by K3YOMI** [comment]
image
Progress!

**Comment by K3YOMI** [comment]
If you could, make another pull request with the new commits. Updated some major stuff including improved organization

**Comment by OnlyNandan** [comment]
yeah sure ill make another pull request

**Pull request closed without merging**
